line-length = 88
target-version = "py312"

select = [
  "E", "W", "F",
  "N",
  "B",
  "I",
  "UP",
  "SIM",
  "C4",
  "RET",
]

ignore = [
  "E501"
]

fix = true

[per-file-ignores]
"**/__init__.py" = ["F401"]
